[workspace]
members = ["crates/protocol", "crates/debugger"]
resolver = "2"

[workspace.package]
edition = "2021"
version = "0.1.0"
license = "MIT"
repository = "https://github.com/Avik-creator/gpuiXwebmcp"

[workspace.dependencies]
chrono = { version = "0.4", features = ["serde"] }
gpui = "0.2.2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
unicode-segmentation = "1"
webmcp-protocol = { path = "crates/protocol" }
