/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GpuiRouteImport } from './routes/gpui'
import { Route as TryRouteImport } from './routes/try'
import { Route as WebmcpRouteImport } from './routes/webmcp'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GpuiRoute = GpuiRouteImport.update({
  id: '/gpui',
  path: '/gpui',
  getParentRoute: () => rootRouteImport,
} as any)
const TryRoute = TryRouteImport.update({
  id: '/try',
  path: '/try',
  getParentRoute: () => rootRouteImport,
} as any)
const WebmcpRoute = WebmcpRouteImport.update({
  id: '/webmcp',
  path: '/webmcp',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/gpui': typeof GpuiRoute
  '/try': typeof TryRoute
  '/webmcp': typeof WebmcpRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/gpui': typeof GpuiRoute
  '/try': typeof TryRoute
  '/webmcp': typeof WebmcpRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/gpui': typeof GpuiRoute
  '/try': typeof TryRoute
  '/webmcp': typeof WebmcpRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/gpui' | '/try' | '/webmcp'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/gpui' | '/try' | '/webmcp'
  id: '__root__' | '/' | '/gpui' | '/try' | '/webmcp'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GpuiRoute: typeof GpuiRoute
  TryRoute: typeof TryRoute
  WebmcpRoute: typeof WebmcpRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gpui': {
      id: '/gpui'
      path: '/gpui'
      fullPath: '/gpui'
      preLoaderRoute: typeof GpuiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/try': {
      id: '/try'
      path: '/try'
      fullPath: '/try'
      preLoaderRoute: typeof TryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/webmcp': {
      id: '/webmcp'
      path: '/webmcp'
      fullPath: '/webmcp'
      preLoaderRoute: typeof WebmcpRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GpuiRoute: GpuiRoute,
  TryRoute: TryRoute,
  WebmcpRoute: WebmcpRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
